### ISSUE TITLE
extend existing model

### ISSUE THREAD

**Issue by jardakotesovec** [OuranosSkia/nemo-page#4]
This module looks very promising :-). Like the idea of models and option of creating custom models, because its usually the case that project needs some specific stuff and doing completely own solution is waste of time.

I am wondering if with nemo-page would be feasible to extend for example element model. I need to often wait until element has full opacity (to do screenshot once animation finished), so it make sense to create such convenient method on element model, so it would be nicely inherited. 

Thanks for feedback.

**Comment by OuranosSkia** [comment]
If you are asking about overwriting (or adding to) the models which currently exist, then that is not really doable the way it is set up right now (though definitely something I will consider for a 2.0 release). If it's a specific function that you think a lot of people could use (or could be generalized to something that would be more broadly useful), I could definitely look at putting that in to the main Element model.

You can extend models though pretty easily to create new model types (it's one of the core features: https://github.com/OuranosSkia/nemo-page#creating-custom-models). I know this probably isn't exactly what you need, but if the large majority of times you use that method is with things that are basic element models (and not one of the extended classes), this would likely meet most of your use cases. (In this case, you could extend the Element model and make your new model have the extra wait function and then just use that wherever necessary).

**Comment by jardakotesovec** [comment]
Thanks a lot for the answer.  I will consider it as option.  I am exploring available frameworks for selenium and webdriver.io v4 also seems like tempting solution.  It surprises me how selenium-webdriver is unfriendly in terms of documentation and api. Nemo definitely makes it more approachable.
